---
- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes

- name: Create Backend Directory
  file:
      path: /home/ubuntu/backend
      state: directory

- name: Extract artifact.tar.gz to EC2 
  unarchive:
      src: artifact.tar.gz
      dest: /home/ubuntu/backend

- name: "Installing Node Dependencies"
  shell: |
    cd /home/ubuntu/backend
    sudo npm i

- name: Start the app
  become: true
  shell: |
    cd /home/ubuntu/backend/dist
    pm2 stop default
    pm2 start npm -- start main.js
  register: execute_node

- name: Print message
  debug:
      msg: "{{ execute_node.stdout_lines }}"

- name: Configure pm2 to start as service
  become: true
  shell: |
    env PATH=$PATH:usr/local/bin pms startup systemd -u ubuntu --hp /home/ubuntu
